#dvc.yaml
stages:
  data_processing:
    cmd: python src/data_processing.py
    deps:
      - src/data_processing.py
      - data/raw/beach_data.csv
    params:
      - base
      - data_processing
    outs:
      - data/processed/ 

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    params:
      - base
      - train
    outs:
      - models/

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test.csv
      - models/model.joblib
    params:
      - base
      - data_processing.target_column
      - evaluate
      - train
    metrics:
      - metrics/metrics.json:
          cache: false
